"""PostgreSQL 数据库迁移：schema_version 版本表 + 顺序执行的迁移脚本。"""

from typing import List, Tuple

import asyncpg

from app.core.logging import setup_logger
from app.db.connection import PostgresPool

logger = setup_logger("db.migrations")

# 基础表结构（首次初始化，PostgreSQL 语法）
_BASE_SCHEMA_STATEMENTS: List[str] = [
    """
    CREATE TABLE IF NOT EXISTS users (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        is_active INTEGER NOT NULL DEFAULT 1,
        is_admin INTEGER NOT NULL DEFAULT 0
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS conversations (
        id TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        title TEXT NOT NULL DEFAULT '未命名对话',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS messages (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
        role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
        content TEXT NOT NULL,
        token_count INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_conv_user ON conversations(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_msg_conv ON messages(conversation_id)",
]

# 迁移脚本列表：(版本号, 描述, SQL语句列表)
# 每个迁移只执行一次，通过 schema_version 表追踪
MIGRATIONS: List[Tuple[int, str, List[str]]] = [
    (
        1,
        "新增 refresh_tokens 与 token_blacklist 表",
        [
            """
            CREATE TABLE IF NOT EXISTS refresh_tokens (
                jti TEXT PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                expires_at TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                revoked INTEGER NOT NULL DEFAULT 0
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS token_blacklist (
                jti TEXT PRIMARY KEY,
                expires_at TEXT NOT NULL,
                blacklisted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens(user_id)",
        ],
    ),
    (
        2,
        "messages 表新增 token_count 字段（兼容旧库）",
        [
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS token_count INTEGER NOT NULL DEFAULT 0",
        ],
    ),
    (
        3,
        "users 表新增 is_admin 字段（兼容旧库）",
        [
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin INTEGER NOT NULL DEFAULT 0",
        ],
    ),
    (
        4,
        "pgvector 扩展与向量存储表",
        [
            "CREATE EXTENSION IF NOT EXISTS vector",
            """
            CREATE TABLE IF NOT EXISTS long_term_memories (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
                content TEXT NOT NULL,
                question TEXT,
                answer TEXT,
                metadata JSONB DEFAULT '{}',
                embedding vector(768),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_ltm_user ON long_term_memories(user_id)",
            """
            CREATE TABLE IF NOT EXISTS rag_chunks (
                id TEXT PRIMARY KEY,
                filename TEXT NOT NULL,
                chunk_index INTEGER NOT NULL,
                content TEXT NOT NULL,
                section_title TEXT DEFAULT '',
                prev_chunk_id TEXT DEFAULT '',
                next_chunk_id TEXT DEFAULT '',
                embedding vector(768),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_rag_filename ON rag_chunks(filename)",
        ],
    ),
    (
        5,
        "工业智能制造 RAG 向量表（与通用 RAG 隔离）",
        [
            """
            CREATE TABLE IF NOT EXISTS mfg_rag_chunks (
                id TEXT PRIMARY KEY,
                filename TEXT NOT NULL,
                chunk_index INTEGER NOT NULL,
                content TEXT NOT NULL,
                section_title TEXT DEFAULT '',
                prev_chunk_id TEXT DEFAULT '',
                next_chunk_id TEXT DEFAULT '',
                embedding vector(768),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_mfg_rag_filename ON mfg_rag_chunks(filename)",
        ],
    ),
    (
        6,
        "会话类型区分（general/mfg）+ 消息图片字段",
        [
            "ALTER TABLE conversations ADD COLUMN IF NOT EXISTS conv_type TEXT NOT NULL DEFAULT 'general'",
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS image_filename TEXT NOT NULL DEFAULT ''",
            "CREATE INDEX IF NOT EXISTS idx_conv_type ON conversations(user_id, conv_type)",
        ],
    ),
]


async def _ensure_schema_version_table(pool: PostgresPool) -> None:
    """创建 schema_version 追踪表（幂等）。"""
    async with pool.acquire() as conn:
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS schema_version (
                version INTEGER PRIMARY KEY,
                description TEXT NOT NULL,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """)


async def _get_applied_versions(pool: PostgresPool) -> set:
    """获取已应用的迁移版本号。"""
    rows = await pool.fetch_all("SELECT version FROM schema_version")
    return {row["version"] for row in rows}


async def run_migrations(pool: PostgresPool) -> None:
    """
    执行数据库迁移：
    1. 创建基础表结构（幂等）
    2. 创建 schema_version 追踪表
    3. 顺序执行未应用的迁移脚本
    """
    # 创建基础表（逐条 DDL 执行，asyncpg 不支持 executescript）
    async with pool.acquire() as conn:
        for stmt in _BASE_SCHEMA_STATEMENTS:
            await conn.execute(stmt)

    # 确保 schema_version 表存在
    await _ensure_schema_version_table(pool)

    # 获取已应用的版本
    applied_versions = await _get_applied_versions(pool)

    # 顺序执行未应用的迁移
    for version, description, statements in MIGRATIONS:
        if version in applied_versions:
            continue
        try:
            async with pool.acquire() as conn:
                for stmt in statements:
                    await conn.execute(stmt)
                await conn.execute(
                    "INSERT INTO schema_version (version, description) VALUES ($1, $2) "
                    "ON CONFLICT (version) DO NOTHING",
                    version,
                    description,
                )
            logger.info("迁移已应用 [v%d]: %s", version, description)
        except asyncpg.DuplicateColumnError:
            # ALTER TABLE 重复执行（字段已存在），视为已应用
            async with pool.acquire() as conn:
                await conn.execute(
                    "INSERT INTO schema_version (version, description) VALUES ($1, $2) "
                    "ON CONFLICT (version) DO NOTHING",
                    version,
                    description,
                )
            logger.info("迁移 [v%d] 字段已存在，标记为已应用", version)
        except Exception as e:
            logger.error("迁移 [v%d] 失败: %s", version, e)
            raise

    logger.info("数据库迁移检查完成")
