"""PostgreSQL 数据库迁移：schema_version 版本表 + 顺序执行的迁移脚本。"""

from typing import List, Tuple  # 导入类型注解：列表与元组类型

import asyncpg  # 导入 asyncpg 驱动，用于捕获特定异常（如 DuplicateColumnError）

from app.core.logging import setup_logger  # 导入日志初始化函数
from app.db.connection import PostgresPool  # 导入连接池类型，作为迁移函数参数类型注解

logger = setup_logger("db.migrations")  # 创建名为 db.migrations 的日志记录器实例

# 基础表结构（首次初始化，PostgreSQL 语法）
_BASE_SCHEMA_STATEMENTS: List[str] = [  # 基础建表语句列表，首次启动时逐条执行
    # 创建 users 表：自增主键、唯一用户名、密码哈希、创建时间、是否启用、是否为管理员
    """
    CREATE TABLE IF NOT EXISTS users (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        is_active INTEGER NOT NULL DEFAULT 1,
        is_admin INTEGER NOT NULL DEFAULT 0
    )
    """,
    # 创建 conversations 表：文本主键、关联用户、标题、创建与更新时间
    """
    CREATE TABLE IF NOT EXISTS conversations (
        id TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        title TEXT NOT NULL DEFAULT '未命名对话',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
    """,
    # 创建 messages 表：自增主键、关联会话（级联删除）、角色约束、内容、token 计数、创建时间
    """
    CREATE TABLE IF NOT EXISTS messages (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
        role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
        content TEXT NOT NULL,
        token_count INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_conv_user ON conversations(user_id)",  # 为会话表的 user_id 创建索引以加速按用户查询
    "CREATE INDEX IF NOT EXISTS idx_msg_conv ON messages(conversation_id)",  # 为消息表的 conversation_id 创建索引以加速按会话查询
]

# 迁移脚本列表：(版本号, 描述, SQL语句列表)
# 每个迁移只执行一次，通过 schema_version 表追踪
MIGRATIONS: List[Tuple[int, str, List[str]]] = [  # 增量迁移脚本列表，每项为 (版本号, 描述, SQL 列表)
    (
        1,  # 迁移版本号
        "新增 refresh_tokens 与 token_blacklist 表",  # 迁移描述
        [  # 该迁移包含的 SQL 语句列表
            # 创建 refresh_tokens 表：jti 主键、关联用户（级联删除）、过期时间、创建时间、是否撤销
            """
            CREATE TABLE IF NOT EXISTS refresh_tokens (
                jti TEXT PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                expires_at TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                revoked INTEGER NOT NULL DEFAULT 0
            )
            """,
            # 创建 token_blacklist 表：jti 主键、过期时间、加入黑名单时间
            """
            CREATE TABLE IF NOT EXISTS token_blacklist (
                jti TEXT PRIMARY KEY,
                expires_at TEXT NOT NULL,
                blacklisted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens(user_id)",  # 为刷新令牌表的 user_id 创建索引
        ],
    ),
    (
        2,  # 迁移版本号
        "messages 表新增 token_count 字段（兼容旧库）",  # 迁移描述
        [  # SQL 语句列表
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS token_count INTEGER NOT NULL DEFAULT 0",  # 为消息表添加 token_count 列（兼容旧库）
        ],
    ),
    (
        3,  # 迁移版本号
        "users 表新增 is_admin 字段（兼容旧库）",  # 迁移描述
        [  # SQL 语句列表
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin INTEGER NOT NULL DEFAULT 0",  # 为用户表添加 is_admin 列（兼容旧库）
        ],
    ),
    (
        4,  # 迁移版本号
        "pgvector 扩展与向量存储表",  # 迁移描述
        [  # SQL 语句列表
            "CREATE EXTENSION IF NOT EXISTS vector",  # 启用 pgvector 扩展（向量类型支持）
            # 创建 long_term_memories 表：长期记忆存储，关联用户、内容、问答、元数据、768 维向量、创建时间
            """
            CREATE TABLE IF NOT EXISTS long_term_memories (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
                content TEXT NOT NULL,
                question TEXT,
                answer TEXT,
                metadata JSONB DEFAULT '{}',
                embedding vector(768),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_ltm_user ON long_term_memories(user_id)",  # 为长期记忆表的 user_id 创建索引
            # 创建 rag_chunks 表：RAG 文档切片存储，含文件名、切片序号、内容、章节标题、前后切片链接、768 维向量
            """
            CREATE TABLE IF NOT EXISTS rag_chunks (
                id TEXT PRIMARY KEY,
                filename TEXT NOT NULL,
                chunk_index INTEGER NOT NULL,
                content TEXT NOT NULL,
                section_title TEXT DEFAULT '',
                prev_chunk_id TEXT DEFAULT '',
                next_chunk_id TEXT DEFAULT '',
                embedding vector(768),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_rag_filename ON rag_chunks(filename)",  # 为 RAG 切片表的 filename 创建索引
        ],
    ),
    (
        5,  # 迁移版本号
        "工业智能制造 RAG 向量表（与通用 RAG 隔离）",  # 迁移描述
        [  # SQL 语句列表
            # 创建 mfg_rag_chunks 表：工业智能制造专用 RAG 切片存储，结构与 rag_chunks 相同
            """
            CREATE TABLE IF NOT EXISTS mfg_rag_chunks (
                id TEXT PRIMARY KEY,
                filename TEXT NOT NULL,
                chunk_index INTEGER NOT NULL,
                content TEXT NOT NULL,
                section_title TEXT DEFAULT '',
                prev_chunk_id TEXT DEFAULT '',
                next_chunk_id TEXT DEFAULT '',
                embedding vector(768),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_mfg_rag_filename ON mfg_rag_chunks(filename)",  # 为工业 RAG 切片表的 filename 创建索引
        ],
    ),
    (
        6,  # 迁移版本号
        "会话类型区分（general/mfg）+ 消息图片字段",  # 迁移描述
        [  # SQL 语句列表
            "ALTER TABLE conversations ADD COLUMN IF NOT EXISTS conv_type TEXT NOT NULL DEFAULT 'general'",  # 为会话表添加 conv_type 列，区分通用与工业场景
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS image_filename TEXT NOT NULL DEFAULT ''",  # 为消息表添加 image_filename 列，支持图片消息
            "CREATE INDEX IF NOT EXISTS idx_conv_type ON conversations(user_id, conv_type)",  # 创建 (user_id, conv_type) 复合索引加速按类型查询
        ],
    ),
    (
        7,  # 迁移版本号
        "混合检索全文索引（rag_chunks + long_term_memories 的 tsvector/GIN/触发器）",  # 迁移描述
        [  # SQL 语句列表
            # ---- rag_chunks 表全文检索支持 ----
            "ALTER TABLE rag_chunks ADD COLUMN IF NOT EXISTS tsv tsvector",  # 为 rag_chunks 添加 tsvector 全文检索列
            "UPDATE rag_chunks SET tsv = to_tsvector('simple', content)",  # 用 content 内容填充现有行的 tsv 列
            "CREATE INDEX IF NOT EXISTS idx_rag_chunks_tsv ON rag_chunks USING GIN(tsv)",  # 为 tsv 列创建 GIN 索引加速全文检索
            # rag_chunks 触发器函数：INSERT/UPDATE 时自动更新 tsv 列
            "CREATE OR REPLACE FUNCTION update_tsv_rag_chunks() RETURNS trigger AS $$ BEGIN NEW.tsv = to_tsvector('simple', NEW.content); RETURN NEW; END; $$ LANGUAGE plpgsql",  # 创建自动更新tsv的触发器函数
            "DROP TRIGGER IF EXISTS trg_rag_chunks_tsv ON rag_chunks",  # 删除已存在的同名触发器（幂等）
            "CREATE TRIGGER trg_rag_chunks_tsv BEFORE INSERT OR UPDATE ON rag_chunks FOR EACH ROW EXECUTE FUNCTION update_tsv_rag_chunks()",  # 创建触发器：插入或更新时自动维护 tsv
            # ---- long_term_memories 表全文检索支持 ----
            "ALTER TABLE long_term_memories ADD COLUMN IF NOT EXISTS tsv tsvector",  # 为 long_term_memories 添加 tsvector 全文检索列
            "UPDATE long_term_memories SET tsv = to_tsvector('simple', content)",  # 用 content 内容填充现有行的 tsv 列
            "CREATE INDEX IF NOT EXISTS idx_long_term_memories_tsv ON long_term_memories USING GIN(tsv)",  # 为 tsv 列创建 GIN 索引加速全文检索
            # long_term_memories 触发器函数：INSERT/UPDATE 时自动更新 tsv 列
            "CREATE OR REPLACE FUNCTION update_tsv_long_term_memories() RETURNS trigger AS $$ BEGIN NEW.tsv = to_tsvector('simple', NEW.content); RETURN NEW; END; $$ LANGUAGE plpgsql",  # 创建自动更新tsv的触发器函数
            "DROP TRIGGER IF EXISTS trg_long_term_memories_tsv ON long_term_memories",  # 删除已存在的同名触发器（幂等）
            "CREATE TRIGGER trg_long_term_memories_tsv BEFORE INSERT OR UPDATE ON long_term_memories FOR EACH ROW EXECUTE FUNCTION update_tsv_long_term_memories()",  # 创建触发器：插入或更新时自动维护 tsv
        ],
    ),
]


async def _ensure_schema_version_table(pool: PostgresPool) -> None:
    """创建 schema_version 追踪表（幂等）。"""
    async with pool.acquire() as conn:  # 从连接池获取一个连接
        # 执行建表 SQL：schema_version 表用于记录已应用的迁移版本
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS schema_version (
                version INTEGER PRIMARY KEY,
                description TEXT NOT NULL,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """)  # 若表已存在则不创建（IF NOT EXISTS 保证幂等）


async def _get_applied_versions(pool: PostgresPool) -> set:
    """获取已应用的迁移版本号。"""
    rows = await pool.fetch_all("SELECT version FROM schema_version")  # 查询所有已记录的迁移版本
    return {row["version"] for row in rows}  # 将版本号收集为集合返回，便于快速判断


async def run_migrations(pool: PostgresPool) -> None:
    """
    执行数据库迁移：
    1. 创建基础表结构（幂等）
    2. 创建 schema_version 追踪表
    3. 顺序执行未应用的迁移脚本
    """
    # 创建基础表（逐条 DDL 执行，asyncpg 不支持 executescript）
    async with pool.acquire() as conn:  # 从连接池获取一个连接用于执行基础建表
        for stmt in _BASE_SCHEMA_STATEMENTS:  # 遍历基础建表语句列表
            await conn.execute(stmt)  # 逐条执行 DDL 语句

    # 确保 schema_version 表存在
    await _ensure_schema_version_table(pool)  # 创建迁移版本追踪表（若不存在）

    # 获取已应用的版本
    applied_versions = await _get_applied_versions(pool)  # 查询已应用的迁移版本集合

    # 顺序执行未应用的迁移
    for version, description, statements in MIGRATIONS:  # 遍历所有迁移脚本
        if version in applied_versions:  # 若该版本已应用则跳过
            continue
        try:  # 尝试执行该版本的所有 SQL
            async with pool.acquire() as conn:  # 获取连接，所有 SQL 在同一连接上执行
                for stmt in statements:  # 逐条执行迁移 SQL
                    await conn.execute(stmt)
                await conn.execute(  # 记录该版本已应用
                    "INSERT INTO schema_version (version, description) VALUES ($1, $2) "
                    "ON CONFLICT (version) DO NOTHING",
                    version,  # 版本号占位符
                    description,  # 描述占位符
                )
            logger.info("迁移已应用 [v%d]: %s", version, description)  # 记录迁移成功日志
        except asyncpg.DuplicateColumnError:  # ALTER TABLE 添加列时该列已存在
            # ALTER TABLE 重复执行（字段已存在），视为已应用
            async with pool.acquire() as conn:  # 重新获取连接以记录版本
                await conn.execute(  # 仍将该版本标记为已应用
                    "INSERT INTO schema_version (version, description) VALUES ($1, $2) "
                    "ON CONFLICT (version) DO NOTHING",
                    version,  # 版本号占位符
                    description,  # 描述占位符
                )
            logger.info("迁移 [v%d] 字段已存在，标记为已应用", version)  # 记录字段已存在的提示日志
        except Exception as e:  # 其他异常
            logger.error("迁移 [v%d] 失败: %s", version, e)  # 记录迁移失败的错误日志
            raise  # 重新抛出异常，终止迁移流程

    logger.info("数据库迁移检查完成")  # 记录所有迁移检查完成的日志